contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #uosnanoclust channel"
    url: https://nfcore.slack.com/channels/uosnanoclust
    about: Discussion about the nf-core/uosnanoclust pipeline
